---

- name: Verify df works
  become: true
  command: timeout 15 df
  register: df_res
  failed_when: false
  changed_when: false
  tags: always

- name: Warning for df
  set_fact:
     my_bads: '{{ my_bads + [ "There is an mount that does not work." ] }}'
  when:
     - df_res.rc != 0
  tags: always

- name: verify mount -a works
  become: true
  command: timeout 15 mount -a
  register: mount_a
  failed_when: false
  changed_when: false
  tags: always

- block:
  - name: Warning for mount
    set_fact:
      my_bads: '{{ my_bads + [ "A configured mount that does not work." ] }}'

  - name: Include mount error
    set_fact:
      my_bads: "{{ my_bads + [ ' - Details: ' + mount_a.stderr ] }}"

  when:
     - mount_a.rc != 0

- name: Check for duplicate volumes in /etc/fstab
  shell: grep -oE '^[^#]\S+' /etc/fstab | sort | uniq -d
  changed_when: false
  register: dup_fs

- block:
  - name: Include the duplicate volume warning
    set_fact:
      my_bads: "{{ my_bads + [ 'There are duplicate entries in your /etc/fstab file.' ] }}"
  - name: Include the details
    set_fact:
       my_bads: "{{ my_bads + [ ' - Details: ' + dup_fs.stdout ] }}"
  when:
     - dup_fs.stdout
     - dup_fs.stdout | length > 0
     - "'proc' not in dup_fs.stdout"
     - "'tmpfs' not in dup_fs.stdout"
